
# "$schema" = 'https://starship.rs/config-schema.json'

# AWS Module
[aws]
symbol = "îŒ½  "

# Buf Module
[buf]
symbol = "ï’ "

# C Module
[c]
symbol = "î˜ "

# Command Duration Module
[cmd_duration]
format = '\[[ï¨š$duration]($style)\] '

# Conda Module
[conda]
symbol = "ï„Œ "

# Dart Module
[dart]
symbol = "î˜ "

# Directory Module
[directory]
read_only = " ï ½"

# Docker Context module
[docker_context]
symbol = "ïŒˆ "

# Elixir Module
[elixir]
symbol = "î‰µ "

# Elm Module
[elm]
symbol = "î˜¬ "

# Git Branch Module
[git_branch]
symbol = "ï˜ "
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'

# Go Module
[golang]
symbol = "î˜§ "

# Haskell Module
[haskell]
symbol = "î· "

# Java Module
[java]
symbol = "î‰– "

# Julia Module
[julia]
symbol = "î˜¤ "
format = '\[[$symbol($version)]($style)\] '

# Lua module
[lua]
symbol = "î˜  "
format = '\[[$symbol($version)]($style)\] '

# Memory Usage Module
[memory_usage]
symbol = "ï¡š "

# Nim Module
[nim]
symbol = "ïš¤ "

# Nix-shell Module
[nix_shell]
symbol = "ï‹œ "

# Node.js Module
[nodejs]
symbol = "îœ˜ "

# Package Version Module
[package]
symbol = "ï£– "

# Python Module
[python]
symbol = "îˆµ "
format = '\[[$symbol($version)]($style)\] '

# R Module
[rlang]

symbol = "\ufcd2 "
format = '\[[$symbol($version)]($style)\] '
detect_files = [""]

# Spack Module
[spack]
symbol = "ğŸ…¢ "

# Rust Module
[rust]
symbol = "î¨ "
